import Foundation

public struct CodexProjectionMaterializer: Sendable {
    private static let generatedHeader = "# Generated by OpenPetAgent Codex projection. Do not edit by hand."
    private static let directoryMarker = ".open-pet-agent-generated"

    public init() {}

    public func apply(_ plans: [ProjectionPlan]) throws {
        for plan in plans where plan.engineID == AgentEngineKind.codex.rawValue {
            try apply(plan)
        }
    }

    public func apply(_ plan: ProjectionPlan) throws {
        guard plan.engineID == AgentEngineKind.codex.rawValue else { return }
        for operation in plan.operations {
            try apply(operation)
        }
    }

    private func apply(_ operation: ProjectionOperation) throws {
        switch operation {
        case .writeFile(let contents, let destination):
            try ensureSafeDestination(destination)
            if FileManager.default.fileExists(atPath: destination.path) {
                let existing = try String(contentsOf: destination, encoding: .utf8)
                guard existing.hasPrefix(Self.generatedHeader) else {
                    throw CodexProjectionMaterializerError.unownedDestination(destination)
                }
            }
            try FileManager.default.createDirectory(
                at: destination.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            try "\(Self.generatedHeader)\n\n\(contents)".write(to: destination, atomically: true, encoding: .utf8)

        case .copyDirectory(let source, let destination):
            try replaceGeneratedDirectory(destination) {
                try FileManager.default.copyItem(at: source, to: destination)
            }

        case .symlinkDirectory(let source, let destination):
            try replaceGeneratedDirectory(destination) {
                try FileManager.default.createSymbolicLink(at: destination, withDestinationURL: source)
            }

        case .removeGenerated(let url):
            try ensureSafeDestination(url)
            if FileManager.default.fileExists(atPath: url.path) {
                try FileManager.default.removeItem(at: url)
            }
        }
    }

    private func replaceGeneratedDirectory(_ destination: URL, with write: () throws -> Void) throws {
        try ensureSafeDestination(destination)
        if FileManager.default.fileExists(atPath: destination.path) {
            guard isGeneratedDirectory(destination) else {
                throw CodexProjectionMaterializerError.unownedDestination(destination)
            }
            try FileManager.default.removeItem(at: destination)
        }
        try FileManager.default.createDirectory(
            at: destination.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try write()
        try "generated".write(
            to: destination.appendingPathComponent(Self.directoryMarker),
            atomically: true,
            encoding: .utf8
        )
    }

    private func isGeneratedDirectory(_ destination: URL) -> Bool {
        FileManager.default.fileExists(atPath: destination.appendingPathComponent(Self.directoryMarker).path)
    }

    private func ensureSafeDestination(_ destination: URL) throws {
        guard let root = codexProjectRoot(for: destination) else { return }
        let resolvedRoot = root.standardizedFileURL.resolvingSymlinksInPath()
        let parent = destination.deletingLastPathComponent()
        if FileManager.default.fileExists(atPath: parent.path) {
            let resolvedParent = parent.standardizedFileURL.resolvingSymlinksInPath()
            guard ProjectionTrust.isPath(resolvedParent, inside: resolvedRoot) else {
                throw CodexProjectionMaterializerError.destinationEscapesProject(destination)
            }
        }
        if FileManager.default.fileExists(atPath: destination.path) {
            let resolvedDestination = destination.standardizedFileURL.resolvingSymlinksInPath()
            guard ProjectionTrust.isPath(resolvedDestination, inside: resolvedRoot) else {
                throw CodexProjectionMaterializerError.destinationEscapesProject(destination)
            }
        }
    }

    private func codexProjectRoot(for destination: URL) -> URL? {
        if destination.lastPathComponent == "config.toml",
           destination.deletingLastPathComponent().lastPathComponent == ".codex" {
            return destination.deletingLastPathComponent().deletingLastPathComponent()
        }

        let skills = destination.deletingLastPathComponent()
        let agents = skills.deletingLastPathComponent()
        if skills.lastPathComponent == "skills", agents.lastPathComponent == ".agents" {
            return agents.deletingLastPathComponent()
        }
        return nil
    }
}

public enum CodexProjectionMaterializerError: Error, Equatable, CustomStringConvertible {
    case destinationEscapesProject(URL)
    case unownedDestination(URL)

    public var description: String {
        switch self {
        case .destinationEscapesProject(let url): return "Codex projection destination escapes project: \(url.path)"
        case .unownedDestination(let url): return "Codex projection destination is not generated by OpenPetAgent: \(url.path)"
        }
    }
}
