import Foundation

/// Codex 投影落盘。ownership 判定走 `.open-pet-agent/state/generated-targets.json`
/// 清单(见 `ProjectionGeneratedManifest.swift`),不在工程根/技能目录写任何 bookkeeping 文件;
/// `config.toml` 保留首行 generated header(文件内自描述「请勿手改」提示,零额外文件)。
public struct CodexProjectionMaterializer: Sendable {
    private static let generatedHeader = "# Generated by OpenPetAgent Codex projection. Do not edit by hand."

    public init() {}

    public func apply(_ plans: [ProjectionPlan]) throws {
        for plan in plans where plan.engineID == AgentEngineKind.codex.rawValue {
            try apply(plan)
        }
    }

    public func apply(_ plan: ProjectionPlan) throws {
        guard plan.engineID == AgentEngineKind.codex.rawValue else { return }
        for operation in plan.operations {
            try apply(operation, engineID: plan.engineID)
        }
    }

    private func apply(_ operation: ProjectionOperation, engineID: String) throws {
        switch operation {
        case .writeFile(let contents, let destination):
            let projectRoot = try ensureSafeDestination(destination)
            if FileManager.default.fileExists(atPath: destination.path) {
                let existing = try String(contentsOf: destination, encoding: .utf8)
                guard existing.hasPrefix(Self.generatedHeader)
                        || isOwned(destination, projectRoot: projectRoot) else {
                    throw CodexProjectionMaterializerError.unownedDestination(destination)
                }
            }
            try FileManager.default.createDirectory(
                at: destination.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            // 先登记再写 payload;簿记失败静默放行,不阻断 materialize。
            if let projectRoot {
                ProjectionGeneratedManifestStore.claimBestEffort(destination, kind: .file, engineID: engineID, projectRoot: projectRoot)
            }
            try "\(Self.generatedHeader)\n\n\(contents)".write(to: destination, atomically: true, encoding: .utf8)

        case .copyDirectory(let source, let destination):
            try replaceGeneratedDirectory(destination, engineID: engineID) {
                try FileManager.default.copyItem(at: source, to: destination)
            }

        case .symlinkDirectory(let source, let destination):
            try replaceGeneratedDirectory(destination, engineID: engineID) {
                try FileManager.default.createSymbolicLink(at: destination, withDestinationURL: source)
            }

        case .removeGenerated(let url):
            let projectRoot = try ensureSafeDestination(url)
            if FileManager.default.fileExists(atPath: url.path) {
                try FileManager.default.removeItem(at: url)
            }
            if let projectRoot {
                ProjectionGeneratedManifestStore.releaseBestEffort(url, projectRoot: projectRoot)
            }
        }
    }

    private func replaceGeneratedDirectory(_ destination: URL, engineID: String, with write: () throws -> Void) throws {
        let projectRoot = try ensureSafeDestination(destination)
        if FileManager.default.fileExists(atPath: destination.path) {
            guard isOwned(destination, projectRoot: projectRoot) else {
                throw CodexProjectionMaterializerError.unownedDestination(destination)
            }
            try FileManager.default.removeItem(at: destination)
        }
        try FileManager.default.createDirectory(
            at: destination.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try write()
        // 目录落地后再登记;簿记失败静默放行,不阻断 materialize。
        if let projectRoot {
            ProjectionGeneratedManifestStore.claimBestEffort(destination, kind: .directory, engineID: engineID, projectRoot: projectRoot)
        }
    }

    private func isOwned(_ destination: URL, projectRoot: URL?) -> Bool {
        guard let projectRoot else { return false }
        return ProjectionGeneratedManifestStore.isGeneratedTarget(destination, projectRoot: projectRoot)
    }

    private func ensureSafeDestination(_ destination: URL) throws -> URL? {
        guard let root = codexProjectRoot(for: destination) else { return nil }
        let resolvedRoot = root.standardizedFileURL.resolvingSymlinksInPath()
        let parent = destination.deletingLastPathComponent()
        if FileManager.default.fileExists(atPath: parent.path) {
            let resolvedParent = parent.standardizedFileURL.resolvingSymlinksInPath()
            guard ProjectionTrust.isPath(resolvedParent, inside: resolvedRoot) else {
                throw CodexProjectionMaterializerError.destinationEscapesProject(destination)
            }
        }
        if FileManager.default.fileExists(atPath: destination.path) {
            let resolvedDestination = destination.standardizedFileURL.resolvingSymlinksInPath()
            guard ProjectionTrust.isPath(resolvedDestination, inside: resolvedRoot) else {
                throw CodexProjectionMaterializerError.destinationEscapesProject(destination)
            }
        }
        return root
    }

    private func codexProjectRoot(for destination: URL) -> URL? {
        if destination.lastPathComponent == "config.toml",
           destination.deletingLastPathComponent().lastPathComponent == ".codex" {
            return destination.deletingLastPathComponent().deletingLastPathComponent()
        }

        let skills = destination.deletingLastPathComponent()
        let agents = skills.deletingLastPathComponent()
        if skills.lastPathComponent == "skills", agents.lastPathComponent == ".agents" {
            return agents.deletingLastPathComponent()
        }
        return nil
    }
}

public enum CodexProjectionMaterializerError: Error, Equatable, CustomStringConvertible {
    case destinationEscapesProject(URL)
    case unownedDestination(URL)

    public var description: String {
        switch self {
        case .destinationEscapesProject(let url): return "Codex projection destination escapes project: \(url.path)"
        case .unownedDestination(let url): return "Codex projection destination is not generated by OpenPetAgent: \(url.path)"
        }
    }
}
