import XCTest
@testable import AgentMode

final class ProjectCapabilityAuditTests: XCTestCase {
    private var root: URL!
    private var project: AgentProject!

    override func setUp() {
        super.setUp()
        root = FileManager.default.temporaryDirectory
            .appendingPathComponent("ProjectCapabilityAuditTests-\(UUID().uuidString)", isDirectory: true)
        try? FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        project = AgentProject(
            id: "p",
            name: "P",
            rootURL: root.appendingPathComponent("repo", isDirectory: true),
            isExternal: true,
            createdAt: Date(timeIntervalSince1970: 0)
        )
    }

    override func tearDown() {
        if let root { try? FileManager.default.removeItem(at: root) }
        super.tearDown()
    }

    func testMissingStateFileLoadsEmptyAndUsesLocalOnlyPath() throws {
        let store = auditStore()

        let state = try store.load(project: project)

        XCTAssertEqual(state, CapabilityAuditState())
        XCTAssertEqual(
            ProjectConfig.capabilityAuditStateURL(for: project).path,
            project.rootURL.appendingPathComponent(".open-pet-agent/state/capabilities.local.json").path
        )
        XCTAssertFalse(FileManager.default.fileExists(atPath: project.rootURL.appendingPathComponent(".mcp.json").path))
        XCTAssertFalse(FileManager.default.fileExists(atPath: project.rootURL.appendingPathComponent(".codex/config.toml").path))
    }

    func testRecordedGeneratedTargetReportsNoDriftWhenHashMatches() throws {
        let target = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"x\"\n".write(to: target, atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.writeFile(contents: "model = \"x\"", destination: target)]
        )
        let store = auditStore()
        try store.recordSync(project: project, plans: [plan], date: Date(timeIntervalSince1970: 1))

        let diagnostics = try ProjectCapabilityAuditor(store: store).diagnostics(project: project, plans: [plan])

        XCTAssertFalse(diagnostics.contains { $0.message.contains("drift") || $0.message.contains("漂移") })
        XCTAssertEqual(try store.load(project: project).lastSyncDescription, "1970-01-01T00:00:01Z")
    }

    func testRecordedGeneratedTargetReportsDriftWhenContentChanges() throws {
        let target = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"x\"\n".write(to: target, atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.writeFile(contents: "model = \"x\"", destination: target)]
        )
        let store = auditStore()
        try store.recordSync(project: project, plans: [plan], date: Date(timeIntervalSince1970: 1))
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"changed\"\n".write(to: target, atomically: true, encoding: .utf8)

        let diagnostics = try ProjectCapabilityAuditor(store: store).diagnostics(project: project, plans: [plan])

        XCTAssertTrue(diagnostics.contains {
            $0.severity == .warning
                && $0.message.contains("生成目标漂移")
                && $0.path == target.path
        })
    }

    func testUserOwnedTargetConflictIsReportedBeforeMaterializing() throws {
        let target = project.rootURL.appendingPathComponent(".mcp.json", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "{\"mcpServers\":{}}".write(to: target, atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.claudeCode.rawValue,
            pluginID: "claude-code",
            operations: [.writeFile(contents: "{}", destination: target)]
        )

        let diagnostics = try ProjectCapabilityAuditor().diagnostics(project: project, plans: [plan])

        XCTAssertTrue(diagnostics.contains {
            $0.severity == .error
                && $0.message.contains("用户自有目标冲突")
                && $0.path == target.path
        })
    }

    func testRecordSyncMergesTargetsFromSeparateEngines() throws {
        let codexTarget = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        let claudeTarget = project.rootURL.appendingPathComponent(".mcp.json", isDirectory: false)
        try FileManager.default.createDirectory(at: codexTarget.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"x\"\n".write(to: codexTarget, atomically: true, encoding: .utf8)
        try "{}".write(to: claudeTarget, atomically: true, encoding: .utf8)
        let codexPlan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.writeFile(contents: "model = \"x\"", destination: codexTarget)]
        )
        let claudePlan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.claudeCode.rawValue,
            pluginID: "claude-code",
            operations: [.writeFile(contents: "{}", destination: claudeTarget)]
        )
        let store = auditStore()

        try store.recordSync(project: project, plans: [codexPlan], date: Date(timeIntervalSince1970: 1))
        try store.recordSync(project: project, plans: [claudePlan], date: Date(timeIntervalSince1970: 2))

        let paths = try store.load(project: project).generatedTargets.map(\.path).sorted()
        XCTAssertEqual(paths, [claudeTarget.path, codexTarget.path].sorted())
    }

    func testRecordBackupStoresExistingGeneratedTargetBeforeSync() throws {
        let target = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n".write(to: target, atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.writeFile(contents: "model = \"new\"", destination: target)]
        )
        let store = auditStore()
        try own(".codex/config.toml", kind: .file)

        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))

        let state = try store.load(project: project)
        let backup = try XCTUnwrap(state.backups.first)
        XCTAssertEqual(backup.engineID, AgentEngineKind.codex.rawValue)
        XCTAssertEqual(backup.pluginID, "codex")
        XCTAssertEqual(backup.targetPath, target.path)
        XCTAssertTrue(FileManager.default.fileExists(atPath: backup.backupPath))
        XCTAssertEqual(
            try String(contentsOf: URL(fileURLWithPath: backup.backupPath), encoding: .utf8),
            "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n"
        )
    }

    func testRecordBackupFailureKeepsPreviousBackupState() throws {
        let target = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n".write(to: target, atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.writeFile(contents: "model = \"new\"", destination: target)]
        )
        let store = auditStore()
        try own(".codex/config.toml", kind: .file)
        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))
        let firstState = try store.load(project: project)
        try FileManager.default.removeItem(at: target)
        try FileManager.default.createDirectory(at: target, withIntermediateDirectories: true)
        try disown(".codex/config.toml")

        XCTAssertThrowsError(try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 4)))

        XCTAssertEqual(try store.load(project: project), firstState)
    }

    func testRestoreLatestBackupFailsClosedWhenOwnershipIsMissing() throws {
        let target = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n".write(to: target, atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.writeFile(contents: "model = \"new\"", destination: target)]
        )
        let store = auditStore()
        try own(".codex/config.toml", kind: .file)
        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))
        try "model = \"user\"\n".write(to: target, atomically: true, encoding: .utf8)
        try disown(".codex/config.toml")

        XCTAssertThrowsError(try store.restoreLatestBackup(project: project))

        XCTAssertEqual(try String(contentsOf: target, encoding: .utf8), "model = \"user\"\n")
    }

    func testRestoreLatestBackupRestoresGeneratedTarget() throws {
        let target = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n".write(to: target, atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.writeFile(contents: "model = \"new\"", destination: target)]
        )
        let store = auditStore()
        try own(".codex/config.toml", kind: .file)
        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"new\"\n".write(to: target, atomically: true, encoding: .utf8)

        try store.restoreLatestBackup(project: project)

        XCTAssertEqual(
            try String(contentsOf: target, encoding: .utf8),
            "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n"
        )
    }

    func testRestoreLatestBackupRestoresAllTargetsFromLatestSync() throws {
        let config = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        let skill = project.rootURL.appendingPathComponent(".agents/skills/review", isDirectory: true)
        try FileManager.default.createDirectory(at: config.deletingLastPathComponent(), withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: skill, withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n".write(to: config, atomically: true, encoding: .utf8)
        try own(".codex/config.toml", kind: .file)
        try own(".agents/skills/review", kind: .directory)
        try "old skill".write(to: skill.appendingPathComponent("SKILL.md"), atomically: true, encoding: .utf8)
        let source = project.rootURL.appendingPathComponent("source", isDirectory: true)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [
                .writeFile(contents: "model = \"new\"", destination: config),
                .copyDirectory(source: source, destination: skill)
            ]
        )
        let store = auditStore()
        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"new\"\n".write(to: config, atomically: true, encoding: .utf8)
        try FileManager.default.removeItem(at: skill.appendingPathComponent("SKILL.md"))
        try "new skill".write(to: skill.appendingPathComponent("SKILL.md"), atomically: true, encoding: .utf8)

        try store.restoreLatestBackup(project: project)

        XCTAssertEqual(
            try String(contentsOf: config, encoding: .utf8),
            "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n"
        )
        XCTAssertEqual(try String(contentsOf: skill.appendingPathComponent("SKILL.md"), encoding: .utf8), "old skill")
    }

    func testRestoreLatestBackupDoesNotPartiallyRestoreWhenAnyTargetIsUnowned() throws {
        let config = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        let skill = project.rootURL.appendingPathComponent(".agents/skills/review", isDirectory: true)
        try FileManager.default.createDirectory(at: config.deletingLastPathComponent(), withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: skill, withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n".write(to: config, atomically: true, encoding: .utf8)
        try own(".codex/config.toml", kind: .file)
        try own(".agents/skills/review", kind: .directory)
        try "old skill".write(to: skill.appendingPathComponent("SKILL.md"), atomically: true, encoding: .utf8)
        let source = project.rootURL.appendingPathComponent("source", isDirectory: true)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [
                .writeFile(contents: "model = \"new\"", destination: config),
                .copyDirectory(source: source, destination: skill)
            ]
        )
        let store = auditStore()
        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))
        try "model = \"user\"\n".write(to: config, atomically: true, encoding: .utf8)
        try disown(".codex/config.toml")
        try FileManager.default.removeItem(at: skill.appendingPathComponent("SKILL.md"))
        try "new skill".write(to: skill.appendingPathComponent("SKILL.md"), atomically: true, encoding: .utf8)

        XCTAssertThrowsError(try store.restoreLatestBackup(project: project))

        XCTAssertEqual(try String(contentsOf: config, encoding: .utf8), "model = \"user\"\n")
        XCTAssertEqual(try String(contentsOf: skill.appendingPathComponent("SKILL.md"), encoding: .utf8), "new skill")
    }

    func testRecordBackupKeepsMultipleSnapshotsForSameTargetAtSameSecond() throws {
        let target = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.writeFile(contents: "model = \"new\"", destination: target)]
        )
        let store = auditStore()
        try own(".codex/config.toml", kind: .file)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old-1\"\n".write(to: target, atomically: true, encoding: .utf8)
        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old-2\"\n".write(to: target, atomically: true, encoding: .utf8)

        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))

        let backups = try store.load(project: project).backups
        XCTAssertEqual(backups.count, 2)
        XCTAssertEqual(Set(backups.map(\.backupPath)).count, 2)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"new\"\n".write(to: target, atomically: true, encoding: .utf8)

        try store.restoreLatestBackup(project: project)

        XCTAssertEqual(
            try String(contentsOf: target, encoding: .utf8),
            "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old-2\"\n"
        )
    }

    func testRestoreLatestBackupUpdatesRecordedHash() throws {
        let target = project.rootURL.appendingPathComponent(".codex/config.toml", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"old\"\n".write(to: target, atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.writeFile(contents: "model = \"new\"", destination: target)]
        )
        let store = auditStore()
        try own(".codex/config.toml", kind: .file)
        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\nmodel = \"new\"\n".write(to: target, atomically: true, encoding: .utf8)
        try store.recordSync(project: project, plans: [plan], date: Date(timeIntervalSince1970: 4))

        try store.restoreLatestBackup(project: project, date: Date(timeIntervalSince1970: 5))

        XCTAssertEqual(try store.load(project: project).lastSyncDescription, "1970-01-01T00:00:05Z")
        XCTAssertTrue(try ProjectCapabilityAuditor(store: store).diagnostics(project: project, plans: [plan]).isEmpty)
    }

    func testRestoreLatestBackupRejectsSymlinkedParentOutsideProject() throws {
        let target = project.rootURL.appendingPathComponent(".agents/skills/review", isDirectory: true)
        try FileManager.default.createDirectory(at: target, withIntermediateDirectories: true)
        try own(".agents/skills/review", kind: .directory)
        try "old skill".write(to: target.appendingPathComponent("SKILL.md"), atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.codex.rawValue,
            pluginID: "codex",
            operations: [.copyDirectory(source: project.rootURL.appendingPathComponent("source"), destination: target)]
        )
        let store = auditStore()
        try store.recordBackup(project: project, plans: [plan], date: Date(timeIntervalSince1970: 3))
        try FileManager.default.removeItem(at: target)
        try FileManager.default.removeItem(at: target.deletingLastPathComponent())
        let outside = root.appendingPathComponent("outside", isDirectory: true)
        try FileManager.default.createDirectory(at: outside, withIntermediateDirectories: true)
        try FileManager.default.createSymbolicLink(at: target.deletingLastPathComponent(), withDestinationURL: outside)

        XCTAssertThrowsError(try store.restoreLatestBackup(project: project))

        XCTAssertFalse(FileManager.default.fileExists(atPath: outside.appendingPathComponent("review/SKILL.md").path))
    }

    func testAcknowledgementPersistsLocalOnlyAndSuppressesDiagnostic() throws {
        let target = project.rootURL.appendingPathComponent(".mcp.json", isDirectory: false)
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "{\"mcpServers\":{}}".write(to: target, atomically: true, encoding: .utf8)
        let plan = ProjectionPlan(
            projectID: project.id,
            engineID: AgentEngineKind.claudeCode.rawValue,
            pluginID: "claude-code",
            operations: [.writeFile(contents: "{}", destination: target)]
        )
        let store = auditStore()
        let auditor = ProjectCapabilityAuditor(store: store)
        let diagnostic = try XCTUnwrap(auditor.diagnostics(project: project, plans: [plan]).first)

        try store.acknowledge(diagnostic, project: project)

        XCTAssertTrue(try store.load(project: project).acknowledgedDiagnostics.contains(ProjectCapabilityAuditStore.key(for: diagnostic)))
        XCTAssertTrue(try auditor.diagnostics(project: project, plans: [plan]).isEmpty)
        XCTAssertTrue(FileManager.default.fileExists(atPath: ProjectConfig.capabilityAuditStateURL(for: project).path))
        XCTAssertFalse(FileManager.default.fileExists(atPath: project.rootURL.appendingPathComponent(".mcp.json.open-pet-agent-state").path))
    }

    func testSourceConfirmationAllowsMatchingSourceOnlyAndCanBeRevoked() throws {
        let store = auditStore()
        let source = ProjectPluginSourceMetadata(
            kind: .git,
            url: "https://example.com/plugin.git",
            revision: "abc123"
        )
        let changed = ProjectPluginSourceMetadata(
            kind: .git,
            url: "https://example.com/plugin.git",
            revision: "def456"
        )
        let pluginRoot = ProjectConfig.pluginDirectory(for: project, pluginID: "remote")
        try FileManager.default.createDirectory(at: pluginRoot, withIntermediateDirectories: true)
        try Data(#"{ "schemaVersion": 1, "id": "remote", "name": "Remote", "source": { "kind": "git", "url": "https://example.com/plugin.git", "revision": "abc123" }, "enabled": true, "capabilities": [] }"#.utf8)
            .write(to: pluginRoot.appendingPathComponent("plugin.json"), options: .atomic)

        try store.confirmSource(project: project, pluginID: "remote", source: source, date: Date(timeIntervalSince1970: 6))

        XCTAssertTrue(try store.isSourceConfirmed(project: project, pluginID: "remote", source: source))
        XCTAssertFalse(try store.isSourceConfirmed(project: project, pluginID: "remote", source: changed))
        let confirmation = try XCTUnwrap(store.loadSourceConfirmations(project: project).confirmations.first)
        XCTAssertEqual(confirmation.confirmedAtDescription, "1970-01-01T00:00:06Z")
        XCTAssertFalse(FileManager.default.fileExists(atPath: ProjectConfig.capabilityAuditStateURL(for: project).path))
        XCTAssertTrue(FileManager.default.fileExists(atPath: root.appendingPathComponent("source-confirmations/p.json").path))

        try store.revokeSourceConfirmation(project: project, pluginID: "remote")

        XCTAssertFalse(try store.isSourceConfirmed(project: project, pluginID: "remote", source: source))
        XCTAssertTrue(try store.loadSourceConfirmations(project: project).confirmations.isEmpty)
    }

    func testRevokeAllSourceConfirmationsClearsEveryPlugin() throws {
        let store = auditStore()
        let source = ProjectPluginSourceMetadata(kind: .git, revision: "abc123")
        for pluginID in ["remote-a", "remote-b"] {
            let pluginRoot = ProjectConfig.pluginDirectory(for: project, pluginID: pluginID)
            try FileManager.default.createDirectory(at: pluginRoot, withIntermediateDirectories: true)
            try Data("""
            { "schemaVersion": 1, "id": "\(pluginID)", "name": "Remote", "source": { "kind": "git", "revision": "abc123" }, "enabled": true, "capabilities": [] }
            """.utf8).write(to: pluginRoot.appendingPathComponent("plugin.json"), options: .atomic)
            try store.confirmSource(project: project, pluginID: pluginID, source: source, date: Date(timeIntervalSince1970: 6))
        }

        try store.revokeAllSourceConfirmations(project: project)

        XCTAssertTrue(try store.loadSourceConfirmations(project: project).confirmations.isEmpty)
        XCTAssertFalse(try store.isSourceConfirmed(project: project, pluginID: "remote-a", source: source))
        XCTAssertFalse(try store.isSourceConfirmed(project: project, pluginID: "remote-b", source: source))
    }

    func testSourceConfirmationInvalidatesWhenPluginContentChanges() throws {
        let store = auditStore()
        let source = ProjectPluginSourceMetadata(
            kind: .git,
            url: "https://example.com/plugin.git",
            revision: "abc123"
        )
        let pluginRoot = ProjectConfig.pluginDirectory(for: project, pluginID: "remote")
        try FileManager.default.createDirectory(at: pluginRoot, withIntermediateDirectories: true)
        try Data(#"{ "schemaVersion": 1, "id": "remote", "name": "Remote", "source": { "kind": "git", "url": "https://example.com/plugin.git", "revision": "abc123" }, "enabled": true, "capabilities": [] }"#.utf8)
            .write(to: pluginRoot.appendingPathComponent("plugin.json"), options: .atomic)

        try store.confirmSource(project: project, pluginID: "remote", source: source, date: Date(timeIntervalSince1970: 6))
        try Data("changed".utf8).write(to: pluginRoot.appendingPathComponent("extra.txt"), options: .atomic)

        XCTAssertFalse(try store.isSourceConfirmed(project: project, pluginID: "remote", source: source))
    }


    func testSourceContentHashSeparatesPathAndPayloadBoundaries() throws {
        let store = auditStore()
        let left = ProjectConfig.pluginDirectory(for: project, pluginID: "left")
        let right = ProjectConfig.pluginDirectory(for: project, pluginID: "right")
        try FileManager.default.createDirectory(at: left.appendingPathComponent("a", isDirectory: true), withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: right, withIntermediateDirectories: true)
        try Data("bc".utf8).write(to: left.appendingPathComponent("a/b", isDirectory: false), options: .atomic)
        try Data("c".utf8).write(to: right.appendingPathComponent("ab", isDirectory: false), options: .atomic)

        let leftHash = try store.sourceContentHash(project: project, pluginID: "left")
        let rightHash = try store.sourceContentHash(project: project, pluginID: "right")

        XCTAssertNotEqual(leftHash, rightHash)
    }


    func testSourceConfirmationInvalidatesWhenHiddenMCPFileChanges() throws {
        let store = auditStore()
        let source = ProjectPluginSourceMetadata(
            kind: .git,
            url: "https://example.com/plugin.git",
            revision: "abc123"
        )
        let pluginRoot = ProjectConfig.pluginDirectory(for: project, pluginID: "remote")
        try FileManager.default.createDirectory(at: pluginRoot.appendingPathComponent("mcp", isDirectory: true), withIntermediateDirectories: true)
        try Data(#"{ "schemaVersion": 1, "id": "remote", "name": "Remote", "source": { "kind": "git", "url": "https://example.com/plugin.git", "revision": "abc123" }, "enabled": true, "capabilities": ["mcp"], "mcp": ["mcp/.servers.json#filesystem"] }"#.utf8)
            .write(to: pluginRoot.appendingPathComponent("plugin.json"), options: .atomic)
        let hiddenMCP = pluginRoot.appendingPathComponent("mcp/.servers.json")
        try Data(#"{ "mcpServers": { "filesystem": { "type": "local", "command": ["npx"] } } }"#.utf8)
            .write(to: hiddenMCP, options: .atomic)

        try store.confirmSource(project: project, pluginID: "remote", source: source, date: Date(timeIntervalSince1970: 6))
        try Data(#"{ "mcpServers": { "filesystem": { "type": "local", "command": ["evil"] } } }"#.utf8)
            .write(to: hiddenMCP, options: .atomic)

        XCTAssertFalse(try store.isSourceConfirmed(project: project, pluginID: "remote", source: source))
    }

    private func auditStore() -> ProjectCapabilityAuditStore {
        ProjectCapabilityAuditStore { [self] project in
            self.root.appendingPathComponent("source-confirmations", isDirectory: true)
                .appendingPathComponent("\(project.id).json", isDirectory: false)
        }
    }

    /// 播种 ownership 登记(manifest-only:目标先登记才视为 PetAgent 生成)。
    private func own(_ relativePath: String, kind: ProjectionGeneratedTarget.Kind) throws {
        var manifest = (try? ProjectionGeneratedManifestStore.load(projectRoot: project.rootURL)) ?? ProjectionGeneratedManifest()
        manifest.claim(path: relativePath, kind: kind, engineID: AgentEngineKind.codex.rawValue)
        try ProjectionGeneratedManifestStore.save(manifest, projectRoot: project.rootURL)
    }

    /// 撤销 ownership 登记(模拟目标失去生成归属)。
    private func disown(_ relativePath: String) throws {
        var manifest = (try? ProjectionGeneratedManifestStore.load(projectRoot: project.rootURL)) ?? ProjectionGeneratedManifest()
        manifest.release(path: relativePath)
        try ProjectionGeneratedManifestStore.save(manifest, projectRoot: project.rootURL)
    }
}
