import Foundation
import Testing
import Context
import Orchestrator
import Rendering
import RuntimeBridge
@testable import AgentMode
@testable import App

@MainActor
@Suite("ProjectCapabilityAuditIntegration")
struct ProjectCapabilityAuditIntegrationTests {
    @Test("sync：Codex 显式同步后记录 generated target hash")
    func codexSyncRecordsGeneratedTargetHash() throws {
        let fixture = try ProjectCapabilityAuditFixture()
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        #expect(message == "Codex 配置已同步")
        let state = try ProjectCapabilityAuditStore().load(project: fixture.project)
        #expect(state.generatedTargets.map(\.path).contains(
            fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path
        ))
        #expect(state.lastSyncDescription != nil)
    }

    @Test("sync：再次同步前备份现有 generated target")
    func codexSyncBacksUpExistingGeneratedTargetBeforeOverwrite() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "Backup")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )
        _ = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)
        let target = fixture.project.rootURL.appendingPathComponent(".codex/config.toml")
        let firstContents = try String(contentsOf: target, encoding: .utf8)
        try """
        { "mcpServers": { "filesystem": { "type": "local", "command": ["uvx", "changed"], "enabled": true } } }
        """.data(using: .utf8)!.write(to: fixture.pluginRoot.appendingPathComponent("mcp/servers.json"), options: .atomic)

        _ = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        let state = try ProjectCapabilityAuditStore().load(project: fixture.project)
        let backup = try #require(state.backups.last { $0.targetPath == target.path })
        #expect(FileManager.default.fileExists(atPath: backup.backupPath))
        #expect(try String(contentsOf: URL(fileURLWithPath: backup.backupPath), encoding: .utf8) == firstContents)
        #expect(try String(contentsOf: target, encoding: .utf8).contains("changed"))
    }

    @Test("restore：恢复上次同步前的 generated target")
    func restoreLatestProjectCapabilityBackupRestoresPreviousGeneratedTarget() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "Restore")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )
        _ = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)
        let target = fixture.project.rootURL.appendingPathComponent(".codex/config.toml")
        let firstContents = try String(contentsOf: target, encoding: .utf8)
        try """
        { "mcpServers": { "filesystem": { "type": "local", "command": ["uvx", "changed"], "enabled": true } } }
        """.data(using: .utf8)!.write(to: fixture.pluginRoot.appendingPathComponent("mcp/servers.json"), options: .atomic)
        _ = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        let message = delegate.restoreLatestProjectCapabilityBackup(project: fixture.project)

        #expect(message == "已恢复上次项目能力同步备份")
        #expect(try String(contentsOf: target, encoding: .utf8) == firstContents)
    }

    @Test("root：能力管理卡片显示最近同步与 doctor 诊断摘要")
    func rootCardShowsAuditSummary() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "Root")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )
        _ = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)
        let target = fixture.project.rootURL.appendingPathComponent(".codex/config.toml")
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\n[mcp_servers.changed]\ncommand = \"uvx\"\n".write(to: target, atomically: true, encoding: .utf8)

        let state = try MinimalAppDelegate.projectCapabilityCard(for: fixture.project, selectedTab: .skills)

        #expect(state.auditSummary?.lastSyncDescription != nil)
        #expect(state.auditSummary?.warningCount == 1)
        #expect(state.auditSummary?.errorCount == 0)
        #expect(state.auditSummary?.statusText.contains("1 个警告") == true)
    }

    @Test("sync：审计状态写失败不回滚也不伪装 materialize 失败")
    func syncAuditWriteFailureDoesNotMaskMaterializeSuccess() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "AuditFailure")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let statePathParent = ProjectConfig.capabilityAuditStateURL(for: fixture.project).deletingLastPathComponent()
        try FileManager.default.createDirectory(at: statePathParent.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Data("not a directory".utf8).write(to: statePathParent, options: .atomic)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        #expect(message.contains("Codex 配置已同步"))
        #expect(message.contains("审计状态记录失败"))
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path))
    }

    @Test("sync：缺失 MCP 不阻断 Codex 和 Claude Code Skill 同步")
    func syncMissingMCPDoesNotBlockSkillProjection() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "MissingMCP")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        try """
        { "mcpServers": {} }
        """.data(using: .utf8)!.write(to: fixture.pluginRoot.appendingPathComponent("mcp/servers.json"), options: .atomic)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let codexMessage = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)
        let claudeMessage = delegate.syncClaudeCodeProjectionForCurrentProject(project: fixture.project)

        #expect(codexMessage.contains("Codex 配置已同步"))
        #expect(codexMessage.contains("失败") == false)
        #expect(claudeMessage.contains("Claude Code 配置已同步"))
        #expect(claudeMessage.contains("失败") == false)
        #expect(FileManager.default.fileExists(
            atPath: fixture.project.rootURL.appendingPathComponent(".agents/skills/dev-toolkit-code-review/SKILL.md").path
        ))
        #expect(FileManager.default.fileExists(
            atPath: fixture.project.rootURL.appendingPathComponent(".claude/skills/dev-toolkit-code-review/SKILL.md").path
        ))
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path) == false)
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".mcp.json").path) == false)
    }

    @Test("sync：缺失 MCP 文件也不阻断 Skill 同步")
    func syncMissingMCPFileDoesNotBlockSkillProjection() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "MissingMCPFile")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        try FileManager.default.removeItem(at: fixture.pluginRoot.appendingPathComponent("mcp/servers.json"))
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let codexMessage = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)
        let claudeMessage = delegate.syncClaudeCodeProjectionForCurrentProject(project: fixture.project)

        #expect(codexMessage.contains("失败") == false)
        #expect(claudeMessage.contains("失败") == false)
        #expect(FileManager.default.fileExists(
            atPath: fixture.project.rootURL.appendingPathComponent(".agents/skills/dev-toolkit-code-review/SKILL.md").path
        ))
        #expect(FileManager.default.fileExists(
            atPath: fixture.project.rootURL.appendingPathComponent(".claude/skills/dev-toolkit-code-review/SKILL.md").path
        ))
    }

    @Test("sync：未确认远端来源拒绝 materialize")
    func syncRejectsUnconfirmedRemoteSourceBeforeMaterializing() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "UntrustedRemote")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true, sourceJSON: #"{ "kind": "git", "url": "https://example.com/plugin.git", "revision": "abc123" }"#)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        #expect(message.contains("来源需确认"))
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path) == false)
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".agents").path) == false)
        #expect((try? ProjectCapabilityAuditStore().load(project: fixture.project).lastSyncDescription) == nil)
    }

    @Test("sync：未确认 MCP-only 远端来源也拒绝 materialize")
    func syncRejectsUnconfirmedRemoteMCPOnlySourceBeforeMaterializing() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "UntrustedMCPOnly")
        defer { fixture.cleanup() }
        try fixture.writePlugin(
            enabled: true,
            sourceJSON: #"{ "kind": "git", "url": "https://example.com/mcp.git", "revision": "abc123" }"#,
            capabilitiesJSON: #"["mcp"]"#,
            skillsJSON: #"[]"#
        )
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncClaudeCodeProjectionForCurrentProject(project: fixture.project)

        #expect(message.contains("来源需确认"))
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".mcp.json").path) == false)
        #expect((try? ProjectCapabilityAuditStore().load(project: fixture.project).lastSyncDescription) == nil)
    }

    @Test("sync：无可投影能力的未确认来源不阻断可信插件同步")
    func syncIgnoresUntrustedSourceWithoutProjectedCapabilities() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "UntrustedEmpty")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let extra = ProjectConfig.pluginDirectory(for: fixture.project, pluginID: "empty-remote")
        try FileManager.default.createDirectory(at: extra, withIntermediateDirectories: true)
        try Data(#"{ "schemaVersion": 1, "id": "empty-remote", "name": "Empty Remote", "source": { "kind": "git", "revision": "abc123" }, "enabled": true, "capabilities": [], "engines": { "codex": { "enabled": true, "projection": "skills-and-mcp-files" } } }"#.utf8).write(to: extra.appendingPathComponent("plugin.json"), options: .atomic)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        #expect(message == "Codex 配置已同步")
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path))
    }

    @Test("sync：未确认来源声明空 skill refs 不阻断可信插件同步")
    func syncIgnoresUntrustedSourceWithNoProjectedRefs() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "UntrustedNoRefs")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let extra = ProjectConfig.pluginDirectory(for: fixture.project, pluginID: "empty-skill-remote")
        try FileManager.default.createDirectory(at: extra, withIntermediateDirectories: true)
        try Data(#"{ "schemaVersion": 1, "id": "empty-skill-remote", "name": "Empty Skill Remote", "source": { "kind": "git", "revision": "abc123" }, "enabled": true, "capabilities": ["skills"], "skills": [], "engines": { "codex": { "enabled": true, "projection": "skills-and-mcp-files" } } }"#.utf8).write(to: extra.appendingPathComponent("plugin.json"), options: .atomic)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        #expect(message == "Codex 配置已同步")
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path))
    }

    @Test("sync：target gate 跟随 adapter 首个 engine alias")
    func syncTrustGateFollowsFirstEngineAlias() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "AliasOrder")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let extra = ProjectConfig.pluginDirectory(for: fixture.project, pluginID: "alias-remote")
        try FileManager.default.createDirectory(at: extra.appendingPathComponent("skills/code-review", isDirectory: true), withIntermediateDirectories: true)
        try Data("# review\n".utf8).write(to: extra.appendingPathComponent("skills/code-review/SKILL.md"), options: .atomic)
        try Data(#"{ "schemaVersion": 1, "id": "alias-remote", "name": "Alias Remote", "source": { "kind": "git", "revision": "abc123" }, "enabled": true, "capabilities": ["skills"], "skills": ["skills/code-review"], "engines": { "claudeCode": { "enabled": true, "projection": "disabled" }, "claude-code": { "enabled": true, "projection": "skills-and-mcp-files" } } }"#.utf8).write(to: extra.appendingPathComponent("plugin.json"), options: .atomic)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncClaudeCodeProjectionForCurrentProject(project: fixture.project)

        #expect(message == "Claude Code 配置已同步")
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".claude/skills/dev-toolkit-code-review/SKILL.md").path))
    }

    @Test("sync：已本地确认的远端来源允许 materialize")
    func syncAllowsLocallyConfirmedRemoteSource() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "ConfirmedRemote")
        defer { fixture.cleanup() }
        let sourceJSON = #"{ "kind": "git", "url": "https://example.com/plugin.git", "revision": "abc123" }"#
        try fixture.writePlugin(enabled: true, sourceJSON: sourceJSON)
        try ProjectCapabilityAuditStore().confirmSource(
            project: fixture.project,
            pluginID: "dev-toolkit",
            source: ProjectPluginSourceMetadata(
                kind: .git,
                url: "https://example.com/plugin.git",
                revision: "abc123"
            ),
            date: Date(timeIntervalSince1970: 7)
        )
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        #expect(message == "Codex 配置已同步")
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path))
        #expect(try ProjectCapabilityAuditStore().load(project: fixture.project).lastSyncDescription != nil)
    }

    @Test("sync：远端来源变更后旧确认自动失效")
    func syncRejectsRemoteSourceAfterConfirmedTupleChanges() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "ChangedRemote")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true, sourceJSON: #"{ "kind": "git", "url": "https://example.com/plugin.git", "revision": "def456" }"#)
        try ProjectCapabilityAuditStore().confirmSource(
            project: fixture.project,
            pluginID: "dev-toolkit",
            source: ProjectPluginSourceMetadata(
                kind: .git,
                url: "https://example.com/plugin.git",
                revision: "abc123"
            ),
            date: Date(timeIntervalSince1970: 7)
        )
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        #expect(message.contains("来源需确认"))
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path) == false)
    }

    @Test("sync：过期确认自动回到 fail-closed")
    func syncRejectsRemoteSourceAfterConfirmationExpires() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "ExpiredRemote")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true, sourceJSON: #"{ "kind": "git", "url": "https://example.com/plugin.git", "revision": "abc123" }"#)
        try ProjectCapabilityAuditStore().confirmSource(
            project: fixture.project,
            pluginID: "dev-toolkit",
            source: ProjectPluginSourceMetadata(
                kind: .git,
                url: "https://example.com/plugin.git",
                revision: "abc123"
            ),
            date: Date(timeIntervalSince1970: 7),
            expiresAfter: -1
        )
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let message = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)

        #expect(message.contains("来源需确认"))
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path) == false)
    }

    @Test("doctor：打开诊断列会记录最近 validation 时间")
    func diagnosticsPanelRecordsLastValidation() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "Validation")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        _ = delegate.projectCapabilityPanel(for: fixture.project)

        #expect(try ProjectCapabilityAuditStore().load(project: fixture.project).lastValidationDescription != nil)
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".codex/config.toml").path) == false)
        #expect(FileManager.default.fileExists(atPath: fixture.project.rootURL.appendingPathComponent(".mcp.json").path) == false)
    }

    @Test("doctor：诊断列显示已同步生成目标的漂移")
    func diagnosticsPanelShowsDriftForChangedGeneratedTarget() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "Drift")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )
        _ = delegate.syncCodexProjectionForCurrentProject(project: fixture.project)
        let target = fixture.project.rootURL.appendingPathComponent(".codex/config.toml")
        try "# Generated by OpenPetAgent Codex projection. Do not edit by hand.\n\n[mcp_servers.changed]\ncommand = \"uvx\"\n".write(to: target, atomically: true, encoding: .utf8)

        let panel = delegate.projectCapabilityPanel(for: fixture.project)

        #expect(panel.fullText.contains("生成目标漂移"))
        #expect(panel.sections.contains { section in
            section.diagnostics.contains { $0.severity == "warning" && $0.message.contains("生成目标漂移") }
        })
    }

    @Test("doctor：诊断列显示用户自有目标冲突")
    func diagnosticsPanelShowsUserOwnedTargetConflict() throws {
        let fixture = try ProjectCapabilityAuditFixture(prefix: "Conflict")
        defer { fixture.cleanup() }
        try fixture.writePlugin(enabled: true)
        let target = fixture.project.rootURL.appendingPathComponent(".mcp.json")
        try FileManager.default.createDirectory(at: target.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "{\"mcpServers\":{}}".write(to: target, atomically: true, encoding: .utf8)
        let delegate = MinimalAppDelegate(
            rootSystem: .testSystem(),
            userDefaults: fixture.defaults,
            startFrameLoop: { _ in nil },
            showShellWindows: { _ in }
        )

        let panel = delegate.projectCapabilityPanel(for: fixture.project)

        #expect(panel.fullText.contains("用户自有目标冲突"))
        #expect(panel.sections.contains { section in
            section.engineName == "Claude Code"
                && section.status == .failed
                && section.diagnostics.contains { $0.severity == "error" && $0.path == target.path }
        })
    }
}

private struct ProjectCapabilityAuditFixture {
    let root: URL
    let project: AgentProject
    let pluginRoot: URL
    let defaults: UserDefaults
    private let suite: String

    init(prefix: String = "P") throws {
        root = FileManager.default.temporaryDirectory
            .appendingPathComponent("ProjectCapabilityAuditIntegrationTests-\(prefix)-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        project = AgentProject(
            id: "p-\(prefix)",
            name: prefix,
            rootURL: root.appendingPathComponent("repo", isDirectory: true),
            isExternal: true,
            createdAt: Date(timeIntervalSince1970: 0)
        )
        pluginRoot = ProjectConfig.pluginDirectory(for: project, pluginID: "dev-toolkit")
        suite = "ProjectCapabilityAuditIntegrationTests-\(UUID().uuidString)"
        defaults = UserDefaults(suiteName: suite)!
        defaults.removePersistentDomain(forName: suite)
    }

    func cleanup() {
        defaults.removePersistentDomain(forName: suite)
        try? FileManager.default.removeItem(at: root)
    }

    func writePlugin(
        enabled: Bool,
        sourceJSON: String = #"{ "kind": "manual" }"#,
        capabilitiesJSON: String = #"["mcp", "skills"]"#,
        skillsJSON: String = #"["skills/code-review"]"#
    ) throws {
        try FileManager.default.createDirectory(at: pluginRoot.appendingPathComponent("mcp", isDirectory: true), withIntermediateDirectories: true)
        let skillRoot = pluginRoot.appendingPathComponent("skills/code-review", isDirectory: true)
        try FileManager.default.createDirectory(at: skillRoot, withIntermediateDirectories: true)
        try "# code-review\n\nReview staged diffs.\n".data(using: .utf8)!.write(to: skillRoot.appendingPathComponent("SKILL.md"), options: .atomic)
        try """
        { "schemaVersion": 1, "id": "dev-toolkit", "name": "Dev Toolkit", "source": \(sourceJSON), "enabled": \(enabled), "capabilities": \(capabilitiesJSON), "mcp": ["mcp/servers.json#filesystem"], "skills": \(skillsJSON), "engines": { "codex": { "enabled": true, "projection": "skills-and-mcp-files" }, "claude-code": { "enabled": true, "projection": "skills-and-mcp-files" } } }
        """.data(using: .utf8)!.write(to: pluginRoot.appendingPathComponent("plugin.json"), options: .atomic)
        try """
        { "mcpServers": { "filesystem": { "type": "local", "command": ["npx", "-y", "@modelcontextprotocol/server-filesystem"], "enabled": true } } }
        """.data(using: .utf8)!.write(to: pluginRoot.appendingPathComponent("mcp/servers.json"), options: .atomic)
    }
}

private extension AppRootSystem {
    static func testSystem() -> AppRootSystem {
        AppRootSystem(
            snapshot: DesktopSnapshot(),
            windowGraph: .bootstrap,
            companionBootstrap: CompanionBootstrap(
                capabilities: RuntimeCapabilities(),
                initialRenderState: RenderState(
                    petPositionX: 100,
                    petPositionY: 100,
                    petRotation: 0,
                    particleCount: 0,
                    particles: [],
                    contactCount: 0,
                    isSnowEnabled: false
                )
            ),
            runtimeTicker: RuntimeTicker { previousState, _, _ in
                RuntimeTickResult(renderState: previousState, snapshot: DesktopSnapshot())
            },
            conversationResponder: ConversationResponder { _ in "" }
        )
    }
}
